### ISSUE TITLE
add compression

### ISSUE THREAD

**Issue by timeshift92** [roxiness/spassr#10]

**Comment by ghostdevv** [comment]
Hey @timeshift92, I was wondering what you meant by compression?

**Comment by timeshift92** [comment]
at the moment spassr does not allow you to compress responses directly in nodejs, you need to put compression through nginx, but I think it would be more convenient to use some kind of hook for middleware so that you can add your own case, in principle, merge request #11  should solve this

**Comment by ghostdevv** [comment]
#11 was merged, does this not fix it then? @timeshift92

**Comment by timeshift92** [comment]
thanks
