### ISSUE TITLE
Change host from localhost to 0.0.0.0 or any other host.

### ISSUE THREAD

**Issue by Xd-pro** [roxiness/spassr#13]
Is there any way to do this? As far as I'm aware this isn't possible with the current version of SpaSSR using the Routify template. Maybe add a config property?

**Comment by jakobrosenberg** [comment]
Hi @Xd-pro , you should be able to set hots with `ssrOptions`.
```javascript
ssrOptions: {
  host: '0.0.0.0'
}
```

You can read more about SSR options here: https://github.com/roxiness/tossr
