### ISSUE TITLE
Deprecated package is used

### ISSUE THREAD

**Issue by flaggs-kmrmshk** [roxiness/spassr#14]
Hello.
Thank you for providing such a great tool.

The package you are using `@svitejs/vite-plugin-svelte` seems to have been deprecated.
I have confirmed that it is used in `configs/svite.config.js`.
Do you have any plans to support it?

Thanks.

**Comment by jakobrosenberg** [comment]
Hi @kimura-masahiko-flaggs 

Could this be about a different repo? This repo doesn't use Vite AFAIK.

**Comment by flaggs-kmrmshk** [comment]
Thank you for your prompt reply.

The word "use" was an error, sorry.
In the configuration file, there was a description of `@svitejs/vite-plugin-svelte` as a dependent package.
Since this dependency package has already been deprecated, I think it needs to be changed to `@sveltejs/vite-plugin-svelte`.

**Comment by jakobrosenberg** [comment]
Ah, now I see. We should probably add the new version as well.

If you're referring to this file
https://github.com/roxiness/spassr/blob/master/configs/svite.config.js
it detects if Svite is installed and if so provides the shown config.

**Comment by flaggs-kmrmshk** [comment]
That's right. As you said, it would be great if you could add a new version.
Thank you.

**Comment by flaggs-kmrmshk** [comment]
Since you have confirmed, I will close this issue.
