### ISSUE TITLE
How to use `window.crypto` in Server Side version?

### ISSUE THREAD

**Issue by lamualfa** [roxiness/spassr#9]
I need `window.crypto` API in both (SSR & CSR), but in Server Side, i get an error saying that `window.crypto` is not defined. How do is solve it?

I think the problem is in `jsdom` used by `spassr`.
- https://github.com/jsdom/jsdom/issues/1612

**Comment by knopki** [comment]
Looks like you can pass `ssrOptions` to `@roxi/ssr`: https://github.com/roxiness/spassr/blob/v2.1.1/server.js#L20
One of the options is `beforeEval` (Executed before script is evaluated). In this function you can patch dom with some `window.crypto` implementation.

Not tested example:
```js
ssrOptions: {
  beforeEval(dom) {
    dom.window.crypto = require('@trust/webcrypto')
  }
}
```

**Comment by jakobrosenberg** [comment]
`ssrOptions` was actually added because of this issue. ^^

I'm currently adding a file config option to `spassr` so you can put @knopki's example in `spassr.config.js`
